branches:
  except:
    - appveyor

language: cpp
dist: xenial
sudo: false
git:
  depth: 99999  # our build requires a full clone
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main"
        key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
    packages:
      - gcc-9
      - g++-9
      - clang-9
      - libboost-dev
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-mixer-dev
      - libglew-dev
      - zlib1g-dev
      - libpng-dev

cache:
  directories:
    - libs/_protobuf-install

env:
  - MATRIX_EVAL="CC=gcc-9 CXX=g++-9"
  - MATRIX_EVAL="CC=clang-9 CXX=clang++-9"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - nvm install 17

script: ./travis.bash
