branches:
  except:
    - appveyor

language: cpp
dist: trusty
sudo: false
git:
  depth: 99999  # our build requires a full clone
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - libboost-dev
      - libboost-filesystem-dev
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-net-dev
      - libsdl2-mixer-dev
      - libglew-dev
      - zlib1g-dev
      - libpng-dev

env:
  - MATRIX_EVAL="CC=gcc-7 CXX=g++-7"
  - MATRIX_EVAL="CC=clang CXX=clang++"

before_install:
  - eval "${MATRIX_EVAL}"

script: mkdir build && cd build && cmake .. && make -j 2 && ./rwe_test
